/// Builds a fallback leaf value from the DSL.
///
/// Supported forms:
/// - `"text"` => `Option<String>`
/// - `|a, b| => "{a} {b}"` => `Option<I18NDynamicResource<(String, String)>>`
#[doc(hidden)]
#[macro_export]
macro_rules! i18n_leaf_expr {
    ($lit:literal) => {
        Some($lit.to_string())
    };

    (|$($args:ident),+ $(,)?| => $lit:literal) => {
        Some($crate::I18NDynamicResource::new(
            |($($args),+,)| format!($lit)
        ))
    };
}

/// Builds a generated field type from the DSL leaf form.
#[doc(hidden)]
#[macro_export]
macro_rules! i18n_leaf_type {
    (@arg_ty $_arg:ident) => {
        String
    };

    ($lit:literal) => {
        Option<$crate::R>
    };

    (|$($args:ident),+ $(,)?| => $lit:literal) => {
        Option<$crate::DR<($($crate::i18n_leaf_type!(@arg_ty $args)),+,)>>
    };
}

/// Builds a concrete struct literal tree from the fallback DSL.
///
/// Nested type names are generated by concatenating parent + field in CamelCase.
#[doc(hidden)]
#[macro_export]
macro_rules! i18n_build_struct {
    ($type_name:ident { $($body:tt)* }) => {
        $crate::i18n_build_struct!(@collect [$type_name] [] $($body)*)
    };

    (@collect [$type_name:ident] [$($fields:tt)*]) => {
        $type_name { $($fields)* }
    };

    (@collect [$type_name:ident] [$($fields:tt)*] $field:ident { $($nested:tt)* } $(, $($rest:tt)*)?) => {
        ::paste::paste! {
            $crate::i18n_build_struct!(
                @collect [$type_name]
                [
                    $($fields)*
                    $field: $crate::i18n_build_struct!([<$type_name $field:camel>] { $($nested)* }),
                ]
                $($($rest)*)?
            )
        }
    };

    (@collect [$type_name:ident] [$($fields:tt)*] $field:ident : $lit:literal $(, $($rest:tt)*)?) => {
        $crate::i18n_build_struct!(
            @collect [$type_name]
            [
                $($fields)*
                $field: $crate::i18n_leaf_expr!($lit),
            ]
            $($($rest)*)?
        )
    };

    (@collect [$type_name:ident] [$($fields:tt)*] $field:ident : |$($args:ident),+ $(,)?| => $lit:literal $(, $($rest:tt)*)?) => {
        $crate::i18n_build_struct!(
            @collect [$type_name]
            [
                $($fields)*
                $field: $crate::i18n_leaf_expr!(|$($args),+| => $lit),
            ]
            $($($rest)*)?
        )
    };
}

/// Defines the full struct type tree for the fallback DSL.
///
/// Nested type names are generated by concatenating parent + field in CamelCase.
#[doc(hidden)]
#[macro_export]
macro_rules! i18n_define_types {
    ($type_name:ident { $($body:tt)* }) => {
        $crate::i18n_define_types!(@collect [$type_name] [] [] $($body)*);
    };

    (@collect [$type_name:ident] [$($fields:tt)*] [$($nested_defs:tt)*]) => {
        $($nested_defs)*
        #[derive(Debug, Default)]
        pub struct $type_name {
            $($fields)*
        }
    };

    (@collect [$type_name:ident] [$($fields:tt)*] [$($nested_defs:tt)*] $field:ident { $($nested:tt)* } $(, $($rest:tt)*)?) => {
        ::paste::paste! {
            $crate::i18n_define_types!(
                @collect [$type_name]
                [
                    $($fields)*
                    pub $field: [<$type_name $field:camel>],
                ]
                [
                    $($nested_defs)*
                    $crate::i18n_define_types!([<$type_name $field:camel>] { $($nested)* });
                ]
                $($($rest)*)?
            );
        }
    };

    (@collect [$type_name:ident] [$($fields:tt)*] [$($nested_defs:tt)*] $field:ident : $lit:literal $(, $($rest:tt)*)?) => {
        $crate::i18n_define_types!(
            @collect [$type_name]
            [
                $($fields)*
                pub $field: $crate::i18n_leaf_type!($lit),
            ]
            [$($nested_defs)*]
            $($($rest)*)?
        );
    };

    (@collect [$type_name:ident] [$($fields:tt)*] [$($nested_defs:tt)*] $field:ident : |$($args:ident),+ $(,)?| => $lit:literal $(, $($rest:tt)*)?) => {
        $crate::i18n_define_types!(
            @collect [$type_name]
            [
                $($fields)*
                pub $field: $crate::i18n_leaf_type!(|$($args),+| => $lit),
            ]
            [$($nested_defs)*]
            $($($rest)*)?
        );
    };
}

/// Applies locale overrides over a previously built fallback value.
///
/// Supported override forms:
/// - `field { ... }` for nested objects
/// - `field: "text"` for static resources
/// - `field: |a, b| => "{a} {b}"` for dynamic resources
#[doc(hidden)]
#[macro_export]
macro_rules! i18n_apply_overrides {
    ($target:expr $(,)?) => {};

    ($target:expr, $field:ident { $($body:tt)* } $(, $($rest:tt)*)?) => {
        $crate::i18n_apply_overrides!(&mut ($target).$field, $($body)*);
        $crate::i18n_apply_overrides!($target $(, $($rest)*)?);
    };

    ($target:expr, $field:ident : $lit:literal $(, $($rest:tt)*)?) => {
        ($target).$field = $crate::i18n_leaf_expr!($lit);
        $crate::i18n_apply_overrides!($target $(, $($rest)*)?);
    };

    ($target:expr, $field:ident : |$($args:ident),+ $(,)?| => $lit:literal $(, $($rest:tt)*)?) => {
        ($target).$field = $crate::i18n_leaf_expr!(|$($args),+| => $lit);
        $crate::i18n_apply_overrides!($target $(, $($rest)*)?);
    };
}

/// Defines the canonical fallback i18n schema and values from a single DSL source.
///
/// DSL forms:
/// - Nested: `field { ... }`
/// - Static: `field: "text"`
/// - Dynamic: `field: |a, b, c| => "{a} {b} {c}"`
///
/// The macro requires a locale key:
/// - `define_i18n_fallback! { I18NUsage => en ... }`
///
/// Generated items in the current module:
/// - `pub mod <root_type_snake> { pub struct <RootType> { ... } }`
/// - `pub fn <locale_key_lower>() -> <root_type_snake>::<RootType>`
#[macro_export]
macro_rules! define_i18n_fallback {
    (
        $root_type:ident =>
        $locale_key:ident
        $($body:tt)*
    ) => {
        ::paste::paste! {
            pub mod [<$root_type:snake>] {
                $crate::i18n_define_types!($root_type { $($body)* });

                impl $crate::I18NFallback for $root_type {
                    fn fallback() -> Self {
                        $crate::i18n_build_struct!($root_type { $($body)* })
                    }
                }
            }

            pub fn [<$locale_key:lower>]() -> [<$root_type:snake>]::$root_type {
                <[<$root_type:snake>]::$root_type as $crate::I18NFallback>::fallback()
            }
        }
    };
}

/// Defines a sparse locale constructor function by applying DSL overrides over defaults.
///
/// Fields not explicitly overridden remain `None` and are resolved through
/// runtime fallback in `I18NAccess::acquire`.
///
/// Override forms:
/// - `field { ... }`
/// - `field: "text"`
/// - `field: |a, b, c| => "{a} {b} {c}"`
///
/// The macro requires a locale key:
/// - `define_i18n! { I18NUsage => pt ... }`
///
/// It generates:
/// - `pub fn <locale_key_lower>() -> I18NUsage::Value`
#[macro_export]
macro_rules! define_i18n {
    (
        $base_i18n:path =>
        $locale_key:ident
        $($body:tt)*
    ) => {
        ::paste::paste! {
            pub fn [<$locale_key:lower>]() -> $base_i18n::Value {
                let mut locale_i18n = <$base_i18n::Value as ::core::default::Default>::default();
                $crate::i18n_apply_overrides!(&mut locale_i18n, $($body)*);
                locale_i18n
            }
        }
    };
}

/// Generates the locale key enum and the i18n wrapper constructor from locale modules.
///
/// The first module is treated as the default locale variant.
///
/// Locale modules are listed using `|` separators:
/// - `en|pt|ru|anylang`
///
/// Each locale module is expected to expose a constructor function with the same
/// name as the module, as generated by `define_i18n_fallback!` / `define_i18n!`.
///
/// Example:
/// `define_i18n_locales! { I18NUsage => en|pt }`
///
/// It generates a namespace module:
/// - `pub mod I18NUsage { ... }`
/// - `pub type I18NUsage::Value = <default_locale_type>`
/// - `pub enum I18NUsage::Key { en, pt, ... }`
/// - `pub fn I18NUsage::locales() -> I18NWrapper<I18NUsage::Key, I18NUsage::Value>`
#[macro_export]
macro_rules! define_i18n_locales {
    (
        $i18n_usage:ident =>
        $default_locale_mod:ident
        $(| $locale_mod:ident )* $(|)?
    ) => {
        ::paste::paste! {
            #[allow(non_snake_case)]
            pub mod $i18n_usage {
                pub type Value = super::$default_locale_mod::[<$i18n_usage:snake>]::$i18n_usage;

                #[allow(non_camel_case_types)]
                #[derive(Debug, Default, Clone, Copy, Hash, Eq, PartialEq)]
                pub enum Key {
                    #[default]
                    $default_locale_mod,
                    $(
                        $locale_mod,
                    )*
                }

                pub fn locales() -> $crate::I18NWrapper<Key, Value> {
                    $crate::I18NWrapper::new(vec![
                        (Key::$default_locale_mod, super::$default_locale_mod::[<$default_locale_mod:snake>]),
                        $(
                            (Key::$locale_mod, super::$locale_mod::[<$locale_mod:snake>]),
                        )*
                    ])
                }
            }
        }
    };
}

/// Defines a local accessor macro bound to a specific `I18NAccess` value.
#[macro_export]
macro_rules! t_prefix {
    ($dollar:tt$name:ident, $prefix_var:ident $(. $prefix_access:tt)*) => {
        macro_rules! $name {
            ($dollar($access:tt).*) => (
                $prefix_var.acquire(|v| v$(. $prefix_access)* $dollar(. $access)*.as_ref())
            )
        }
    };

    ($dollar:tt $name:ident, $prefix_var:ident $(. $prefix_access:tt)*) => {
        $crate::t_prefix!($dollar$name, $prefix_var $(.$prefix_access)*)
    };

    ($dollar:tt$prefix_var:ident $(.$prefix_access:tt)*) => {
        $crate::t_prefix!($dollar t, $prefix_var $(. $prefix_access)*)
    };
}

/// Reads a translation value from an `I18NAccess` expression.
#[macro_export]
macro_rules! t {
    ($var:ident.$($access:tt).*) => {
        $var.acquire(|v| v.$($access).*.as_ref())
    };
}
