/// Builds a fallback leaf value from the DSL.
///
/// Supported forms:
/// - `"text"` => `Option<String>`
/// - `|a, b| => "{a} {b}"` => `Option<I18NDynamicResource<(String, String)>>`
#[doc(hidden)]
#[macro_export]
macro_rules! i18n_leaf_expr {
    ($lit:literal) => {
        Some($lit.to_string())
    };

    (|$($args:ident),+ $(,)?| => $lit:literal) => {
        Some($crate::I18NDynamicResource::new(
            |($($args),+,)| format!($lit)
        ))
    };
}

/// Builds a generated field type from the DSL leaf form.
#[doc(hidden)]
#[macro_export]
macro_rules! i18n_leaf_type {
    (@arg_ty $_arg:ident) => {
        String
    };

    ($lit:literal) => {
        Option<$crate::R>
    };

    (|$($args:ident),+ $(,)?| => $lit:literal) => {
        Option<$crate::DR<($($crate::i18n_leaf_type!(@arg_ty $args)),+,)>>
    };
}

/// Builds a concrete struct literal tree from the fallback DSL.
///
/// Nested type names are generated by concatenating parent + field in CamelCase.
#[doc(hidden)]
#[macro_export]
macro_rules! i18n_build_struct {
    ($type_name:ident { $($body:tt)* }) => {
        $crate::i18n_build_struct!(@collect [$type_name] [] $($body)*)
    };

    (@collect [$type_name:ident] [$($fields:tt)*]) => {
        $type_name { $($fields)* }
    };

    (@collect [$type_name:ident] [$($fields:tt)*] $field:ident { $($nested:tt)* } $(, $($rest:tt)*)?) => {
        ::paste::paste! {
            $crate::i18n_build_struct!(
                @collect [$type_name]
                [
                    $($fields)*
                    $field: $crate::i18n_build_struct!([<$type_name $field:camel>] { $($nested)* }),
                ]
                $($($rest)*)?
            )
        }
    };

    (@collect [$type_name:ident] [$($fields:tt)*] $field:ident : $lit:literal $(, $($rest:tt)*)?) => {
        $crate::i18n_build_struct!(
            @collect [$type_name]
            [
                $($fields)*
                $field: $crate::i18n_leaf_expr!($lit),
            ]
            $($($rest)*)?
        )
    };

    (@collect [$type_name:ident] [$($fields:tt)*] $field:ident : |$($args:ident),+ $(,)?| => $lit:literal $(, $($rest:tt)*)?) => {
        $crate::i18n_build_struct!(
            @collect [$type_name]
            [
                $($fields)*
                $field: $crate::i18n_leaf_expr!(|$($args),+| => $lit),
            ]
            $($($rest)*)?
        )
    };
}

/// Defines the full struct type tree for the fallback DSL.
///
/// Nested type names are generated by concatenating parent + field in CamelCase.
#[doc(hidden)]
#[macro_export]
macro_rules! i18n_define_types {
    ($type_name:ident { $($body:tt)* }) => {
        $crate::i18n_define_types!(@collect [$type_name] [] [] $($body)*);
    };

    (@collect [$type_name:ident] [$($fields:tt)*] [$($nested_defs:tt)*]) => {
        $($nested_defs)*
        #[derive(Debug)]
        pub struct $type_name {
            $($fields)*
        }
    };

    (@collect [$type_name:ident] [$($fields:tt)*] [$($nested_defs:tt)*] $field:ident { $($nested:tt)* } $(, $($rest:tt)*)?) => {
        ::paste::paste! {
            $crate::i18n_define_types!(
                @collect [$type_name]
                [
                    $($fields)*
                    pub $field: [<$type_name $field:camel>],
                ]
                [
                    $($nested_defs)*
                    $crate::i18n_define_types!([<$type_name $field:camel>] { $($nested)* });
                ]
                $($($rest)*)?
            );
        }
    };

    (@collect [$type_name:ident] [$($fields:tt)*] [$($nested_defs:tt)*] $field:ident : $lit:literal $(, $($rest:tt)*)?) => {
        $crate::i18n_define_types!(
            @collect [$type_name]
            [
                $($fields)*
                pub $field: $crate::i18n_leaf_type!($lit),
            ]
            [$($nested_defs)*]
            $($($rest)*)?
        );
    };

    (@collect [$type_name:ident] [$($fields:tt)*] [$($nested_defs:tt)*] $field:ident : |$($args:ident),+ $(,)?| => $lit:literal $(, $($rest:tt)*)?) => {
        $crate::i18n_define_types!(
            @collect [$type_name]
            [
                $($fields)*
                pub $field: $crate::i18n_leaf_type!(|$($args),+| => $lit),
            ]
            [$($nested_defs)*]
            $($($rest)*)?
        );
    };
}

/// Applies locale overrides over a previously built fallback value.
///
/// Supported override forms:
/// - `field: { ... }` for nested objects
/// - `field: "text"` for static resources
/// - `field: |a, b| => "{a} {b}"` for dynamic resources
#[doc(hidden)]
#[macro_export]
macro_rules! i18n_apply_overrides {
    ($target:expr $(,)?) => {};

    ($target:expr, $field:ident : { $($body:tt)* } $(, $($rest:tt)*)?) => {
        $crate::i18n_apply_overrides!(&mut ($target).$field, $($body)*);
        $crate::i18n_apply_overrides!($target $(, $($rest)*)?);
    };

    ($target:expr, $field:ident : $lit:literal $(, $($rest:tt)*)?) => {
        ($target).$field = $crate::i18n_leaf_expr!($lit);
        $crate::i18n_apply_overrides!($target $(, $($rest)*)?);
    };

    ($target:expr, $field:ident : |$($args:ident),+ $(,)?| => $lit:literal $(, $($rest:tt)*)?) => {
        ($target).$field = $crate::i18n_leaf_expr!(|$($args),+| => $lit);
        $crate::i18n_apply_overrides!($target $(, $($rest)*)?);
    };
}

/// Defines the canonical fallback i18n schema and values from a single DSL source.
///
/// DSL forms:
/// - Nested: `field { ... }`
/// - Static: `field: "text"`
/// - Dynamic: `field: |a, b, c| => "{a} {b} {c}"`
///
/// The generated root type is exported as `pub use <root_type_snake>::<RootType>;`.
#[macro_export]
macro_rules! define_i18n_fallback {
    (
        $root_type:ident =>
        $($body:tt)*
    ) => {
        ::paste::paste! {
            pub mod [<$root_type:snake>] {
                $crate::i18n_define_types!($root_type { $($body)* });

                impl $crate::I18NFallback for $root_type {
                    fn fallback() -> Self {
                        $crate::i18n_build_struct!($root_type { $($body)* })
                    }
                }
            }

            pub use [<$root_type:snake>]::$root_type;
        }
    };
}

/// Creates a locale value by applying DSL overrides over fallback.
///
/// Override forms:
/// - `field: { ... }`
/// - `field: "text"`
/// - `field: |a, b, c| => "{a} {b} {c}"`
#[macro_export]
macro_rules! define_i18n {
    ($base_i18n:path, $($body:tt)*) => {{
        let mut base_i18n = <$base_i18n as $crate::I18NFallback>::fallback();
        $crate::i18n_apply_overrides!(&mut base_i18n, $($body)*);
        base_i18n
    }};
}

/// Defines a local accessor macro bound to a specific `I18NAccess` value.
#[macro_export]
macro_rules! t_prefix {
    ($dollar:tt$name:ident, $prefix_var:ident $(. $prefix_access:tt)*) => {
        macro_rules! $name {
            ($dollar($access:tt).*) => (
                $prefix_var.acquire(|v| v$(. $prefix_access)* $dollar(. $access)*.as_ref())
            )
        }
    };

    ($dollar:tt $name:ident, $prefix_var:ident $(. $prefix_access:tt)*) => {
        $crate::t_prefix!($dollar$name, $prefix_var $(.$prefix_access)*)
    };

    ($dollar:tt$prefix_var:ident $(.$prefix_access:tt)*) => {
        $crate::t_prefix!($dollar t, $prefix_var $(. $prefix_access)*)
    };
}

/// Reads a translation value from an `I18NAccess` expression.
#[macro_export]
macro_rules! t {
    ($var:ident.$($access:tt).*) => {
        $var.acquire(|v| v.$($access).*.as_ref())
    };
}
